### ISSUE TITLE
UTF8 files not handled correctly on Windows

### ISSUE THREAD

**Issue by willjs12** [bgreenlee/pygtail#22]
Thanks for creating this useful utility!  I'm having the following trouble (with proposed solution further below.)
Python version: 3.4
Windows version: 7

Pygtail's _get_next_line method is throwing an exception when reading a UTF8 character from the file being tailed.  In this case, the offending character is a Japanese character.  Example:

>  File "tailpid.py", line 11, in <module>
>  for line in Pygtail(file):
>  File "C:\Python34\lib\site-packages\pygtail\core.py", line 122, in **next**
>    return self.next()
>  File "C:\Python34\lib\site-packages\pygtail\core.py", line 96, in next
>    line = self._get_next_line()
>  File "C:\Python34\lib\site-packages\pygtail\core.py", line 241, in _get_next_line
>    line = self._filehandle().readline()
>  File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
>    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
> UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 14: character maps to ><undefined>

Based on some reading on stack overflow, I surmise that this is a problem particular to Windows.  You'll note in the above trace that the cp1252 character map is being used, when what is really needed is UTF8.

Proposed Solution

I've fixed the issue by updating one line of your code as follows.  You may want to consider incorporating this in Pygtail (maybe as an option).  In the _filehandle method, I added the encoding parameter:

> self._fh = open(filename, "r", encoding='utf8')

Thanks again,
-Jeff

**Comment by bgreenlee** [comment]
Thanks for the report. I'm a bit hesitant to force the encoding, rather than let it use the system default. Maybe an `--encoding` command line parameter?

**Comment by willjs12** [comment]
Yes, that's the way to do it.  Thanks!

**Comment by ChrisBarker-NOAA** [comment]
I found this because I was looking for Windows support -- which is not listed in the PyPi metadata.

But we've been using it successfully on Windows -- and it looks like others are, too. So maybe add it to the metadata?

With regard to this issue -- it's tough encoding is a f-ing nightmare. I don't think the "system encoding" is hardly ever reliable, but I can see the reluctance to hard code an encoding it, either.

My recommendation:
1) add an --encoding command line parameter
2) maybe change the default to utf-8 rather than the system default -- though frankly, I don't know that you can count on utf-8 on *nix either, so ?!?!
3) which brings me to this: use chardet (maybe optionally) to detect the encoding:

https://pypi.org/project/chardet/

Not universally reliable, of course, but probably a better default than either hard-coded or system default.

**Comment by bgreenlee** [comment]
Fixed with acff5b00165e14666f0588e36141aefca8ec177e
